### ISSUE TITLE
Event description not sent on PayPal

### ISSUE THREAD

**Issue by lsmithgo** [eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#126]
The description sent to PayPal is set to "ERROR: Title is not Set" which I think is the default value set in CiviCRM.

This manifests itself in the PayPal receipt email and on PayPal itself.

![Capture](https://user-images.githubusercontent.com/13263543/61332701-d2c22400-a81c-11e9-9d8e-764b89f72f90.JPG)

**Comment by eileenmcnaughton** [comment]
Ouch - is this event or contribution page? CiviCRM 5.15?

**Comment by lsmithgo** [comment]
Both!  Have tested both types.

**Comment by eileenmcnaughton** [comment]
OK - I have a feeling we might have fixed in it civi - possibly 5.15 but I'd have to check

**Comment by eileenmcnaughton** [comment]
Hmm - this should be the core patch that ensures title is set https://github.com/civicrm/civicrm-core/commit/d7188a5d5d24d64b631f39d60411783302b6679d

**Comment by lsmithgo** [comment]
I upgraded to 5.15.1 and verified that the patch was applied to CRM/Contribute/Form/ContributionBase.php, however, this does not appear to have rectified the proble as the Error title message still appears in the PayPal payment email.

**Comment by eileenmcnaughton** [comment]
OK I'll do some testing

**Comment by mwestergaard** [comment]
Just noticed same on 5.17.0. Also visible in the shopping cart pulldown on the PayPal login window.

**Comment by mwestergaard** [comment]
Appears to be working properly in 5.17.4!

**Comment by mwestergaard** [comment]
Oops, I spoke too soon! It's okay on my Dev box at 5.17.4, but I upgraded Prod and still see the issue. I use PayPal Standard, which doesn't show line item detail. On Dev, I now see the title of the CiviCRM Contribution Page as the description for the total amount (same as before Omnipay).

I'll see if I can track down the difference. I try to keep the configurations as close as possible, but there are obvious differences. Both have the same extensions.

Production (Civihosting VM):
Wordpress 5.2.3
CiviCRM 5.17.4
PHP 7.2.21
MySQL 5.7.27

Development (Raspberry PI 4 -- don't laugh ;-)
Wordpress 5.2.3
CiviCRM 5.17.4
PHP 7.3.4-2
MariaDB 10.3.17

**Comment by mwestergaard** [comment]
I believe I found the source of the issue, at least on my system. I first tried backing down to PHP 7.2, although I didn't think that was it. After comparing bunches of settings, I finally realized that my Dev system has "PayPal Checkout" as the default Payment Processor. My Prod system still had "PayPal - Website Payments Standard" as the default. If I make "PayPal Checkout" the default, the title comes through correctly. If I change the default on my Dev system, I can recreate the issue. I'm not smart enough to know why, but I hope this helps.

Also, I noticed that when I edited the Payment Processor to make it the default, the Name field was replaced with "default". I had to re-enter the intended name to save it. I don't know if this is related.

**Comment by mlutfy** [comment]
I think it's because `$form->getTitle()` does not work because the form here is a `CRM_Financial_Form_Payment`.

I used this patch, but it feels like a clunky workaround, and I haven't implemented for Event Registrations yet:

```
diff --git a/CRM/Core/Payment/OmnipayMultiProcessor.php b/CRM/Core/Payment/OmnipayMultiProcessor.php
index a6a93712..39881642 100644
--- a/CRM/Core/Payment/OmnipayMultiProcessor.php
+++ b/CRM/Core/Payment/OmnipayMultiProcessor.php
@@ -308,12 +308,26 @@ class CRM_Core_Payment_OmnipayMultiProcessor extends CRM_Core_Payment_PaymentExt
    * @throws \Civi\Payment\Exception\PaymentProcessorException
    */
   public function buildForm(&$form) {
+    $formTitle = $form->getTitle();
+
+    if ($form->_formName == 'Main') {
+      $form_id = CRM_Utils_Request::retrieveValue('id', 'Positive');
+
+      $contributionPage = \Civi\Api4\ContributionPage::get(FALSE)
+        ->addSelect('frontend_title', 'title')
+        ->addWhere('id', '=', $form_id)
+        ->execute()
+        ->first();
+
+      $formTitle = $contributionPage['frontend_title'] ?? $contributionPage['title'];
+    }
+
     $regions = $this->getProcessorTypeMetadata('regions');
     $jsVariables = [
       'paymentProcessorId' => $this->_paymentProcessor['id'],
       'currency' => $form->getCurrency(),
       'is_test' => $this->_is_test,
-      'title' => $form->getTitle(),
+      'title' => $formTitle,
     ];
     $clientSideCredentials = $this->getProcessorTypeMetadata('client_side_credentials');
     if ($clientSideCredentials) {
```

**Comment by composerjk** [comment]
I just noticed this same issue using PayPal Checkout with the Omnipay Multiprocessor extension. We have Stripe via the Stripe extension as the default. We had one PayPal payment come through with a `description` set, but I think that was because the person tried a recurring payment that failed then when the form was reloaded the description was set. The other two payments that came through showed that `ERROR: Title is not Set` as the `description`.

This was for both a donation contribution and a membership contribution. We have not yet set up events through Civi as those are still going through Eventbrite.

**Comment by composerjk** [comment]
@mlutfy's patch in https://github.com/eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor/issues/126#issuecomment-813477819 does seem to work for the contribution page. Haven't had time to investigate for another potential fix.

**Comment by composerjk** [comment]
For a Membership and Renewal contribution form, since this patch sets the description to the title of the form, the **payment processor description doesn't differentiate between a new membership signup versus a membership renewal.** Our financial folk were used to seeing that detail in prior systems. So, trying to see how to ensure the distinction is there for our payment processors.
